[project]
name = "asdstrat"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pandas>=2.3.1",
    "pandas-stubs==2.3.0.250703",
    "pyarrow>=20.0.0",
    "sphinx>=8.2.3",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
]
